apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "golang-minikube-app.fullname" . }}-config
data:
  APP_NAME: "Golang Minikube App"
  APP_ENV: "development"
  APP_MESSAGE: "Hello Wajid! Your Golang app is running on Kubernetes."
