apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-springboot
  template:
    metadata:
      labels:
        app: simple-springboot
    spec:
      containers:
      - name: simple-springboot
        image: simple-springboot-app:latest
        imagePullPolicy: Never   # <-- Ye line add karo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-springboot-service
spec:
  type: NodePort
  selector:
    app: simple-springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
