apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-minikube-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: golang.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golang-minikube-service
                port:
                  number: 8080
