apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-hello
  template:
    metadata:
      labels:
        app: php-hello
    spec:
      containers:
      - name: php-hello
        image: php-hello-app:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-hello-service
spec:
  type: NodePort
  selector:
    app: php-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30050
