apiVersion: v1
kind: Service
metadata:
  name: simple-dotnet-api-service
spec:
  type: NodePort
  selector:
    app: simple-dotnet-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

