apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dotnet-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-dotnet-api
  template:
    metadata:
      labels:
        app: simple-dotnet-api
    spec:
      containers:
      - name: simple-dotnet-api
        image: simple-dotnet-api:latest
        ports:
        - containerPort: 5000
